base/urls.py
from django.contrib import admin
from django.urls import path, include
from register.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("clients.urls")),
    path("register/", register, name="register"),
    path("", include("django.contrib.auth.urls")),
]

clients/urls.py
from django.urls import path

from . import views


app_name = "clients"
urlpatterns = [
    path("", views.index, name="index"),
    path("policyholders/", views.list_all_clients, name="list-all-clients"),
    path("policyholders/<int:pk>/", views.client_detail, name="client-detail"),
    path("policyholders/new/", views.create_client, name="create-client"),
    path("policyholders/<int:pk>/edit/", views.edit_client, name="edit-client"),
    path("policyholders/<int:pk>/delete/", views.delete_client, name="delete-client"),
    path("policyholders/<int:pk>/insurance/<int:id>/", views.insurance_detail, name="insurance-detail"),
    path("policyholders/<int:pk>/insurance/new", views.create_insurance, name="create-insurance"),
    path("policyholders/<int:pk>/insurance/<int:id>/edit", views.edit_insurance, name="edit-insurance"),
    path("policyholders/<int:pk>/insurance/<int:id>/delete", views.delete_insurance, name="delete-insurance"),
    path("policyholders/<int:pk>/insurance/<int:id>/visa", views.visa, name="visa"),
    path("policyholders/<int:pk>/insurance/<int:id>/mastercard", views.mastercard, name="mastercard"),
    path("policyholders/<int:pk>/insurance/<int:id>/kaspi", views.kaspi, name="kaspi"),
    path("policyholders/<int:pk>/insurance/<int:id>/qiwi", views.qiwi, name="qiwi"),
    path("policyholders/<int:pk>/insurance/<int:id>/payments", views.payments, name="payments"),
]

clients/models.py
from datetime import date

from django.db import models


class Client(models.Model):
    """Class for Client instances"""
    
    name = models.CharField(max_length=200, verbose_name="Name")
    surname = models.CharField(max_length=200, verbose_name="Surname")
    street_address = models.CharField(max_length=200, verbose_name="Address")
    city = models.CharField(max_length=100, verbose_name="City")
    postal_code = models.CharField(max_length=6, verbose_name="Postcode")
    email = models.EmailField(max_length=200, verbose_name="Email")
    phone_number = models.CharField(max_length=16, verbose_name="Phone number")

    def __str__(self):
        return f"{self.name} {self.surname}"

 
class Insurance(models.Model):

    TYPES_OF_INSURANCE = [
        ("Property", "Property insurance"),
        ("Emergency", "Contingency insurance"),
        ("Life", "Life insurance"),
        ("Accident", "Accident insurance"),
        ("Liability", "Liability insurance")
    ]

    insurance_type = models.CharField(max_length=30, choices=TYPES_OF_INSURANCE, verbose_name="Insurance type")
    subject = models.CharField(max_length=100, verbose_name="Subject of insurance")
    amount = models.PositiveIntegerField(verbose_name="Sum insured")
    date_from = models.DateField(default=date.today, verbose_name="Insured from")
    date_to = models.DateField(default=date.today, verbose_name="Insured to")
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.insurance_type}: {self.subject}, {self.amount}"


class Payment(models.Model):
    """Class for Payment system"""

    name = models.CharField(max_length=200, verbose_name="Name")
    surname = models.CharField(max_length=200, verbose_name="Surnmae")
    email = models.EmailField(max_length=200, verbose_name="Email")
    date_to_c = models.DateField(default=date.today, verbose_name="Validity")
    card_number = models.CharField(max_length=20, verbose_name="Card number")
    cvv = models.CharField(max_length=3, verbose_name="CVV")

    def _str_(self):
        return f"{self.name} {self.surname}"

clients/forms.py
from django import forms

from . models import Client, Insurance, Payment


class CreateClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ["name", "surname", "street_address", "city", "postal_code", "email", "phone_number"]


class CreateInsuranceForm(forms.ModelForm):

    class Meta:
        model = Insurance
        fields = ["insurance_type", "subject", "amount", "date_from", "date_to"]


class CreatePaymentForm(forms.ModelForm):
    """Curstom form for Client instance creation."""

    class Meta:
        model = Payment
        fields = ["card_number", "name", "surname", "date_to_c", "cvv", "email"]

clients/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import CreateClientForm, CreateInsuranceForm, CreatePaymentForm
from .models import Client, Insurance, Payment


def index(request):
    """Simple function to render home page"""

    return render(request, "clients/index.html")


"""
CLIENT VIEWS
"""


@login_required
def list_all_clients(request):
    """Renders all clients inside of table with paginator"""

    clients = Client.objects.all()
    paginator = Paginator(clients, 5)

    page_number = request.GET.get('page')
    paginated_clients = paginator.get_page(page_number)

    return render(request, "clients/clients_list.html", {
        "paginated_clients": paginated_clients
    })


@login_required
def client_detail(request, pk):
    """Renders clients detail based on 'pk' parameter - only for authenticated users"""

    client = Client.objects.get(id=pk)
    insurances = Insurance.objects.filter(client_id=pk)
    print(insurances)

    return render(request, "clients/client_detail.html", {
        "client": client,
        "insurances": insurances
    })


@staff_member_required(login_url="/login/")
def create_client(request):
    """Creates new client - for staff users only"""

    form = CreateClientForm()

    if request.method == "POST":
        form = CreateClientForm(request.POST)
        if form.is_valid():
            client = form.save()
            return redirect(f"/policyholders/{client.id}/")

    return render(request, "clients/create_client.html", {
        "form": form
    })


@staff_member_required(login_url="/login/")
def edit_client(request, pk):
    """View for editing client information - for staff users only. CLient is based on 'pk' parameter"""

    client = Client.objects.get(id=pk)
    form = CreateClientForm(instance=client)

    if request.method == "POST":
        form = CreateClientForm(request.POST, instance=client)
        if form.is_valid:
            form.save()
            return redirect(f"/policyholders")
            # return redirect(f"") # /insurance/{client.id}/

    return render(request, "clients/client_edit.html", {
        "client": client,
        "form": form
    })


@staff_member_required(login_url="/login/")
def delete_client(request, pk):
    """View that redirects to 'delete client confirmation page' - for staff users only. CLient is based on 'pk' parameter"""

    client = Client.objects.get(id=pk)

    if request.method == "POST":
        client.delete()
        return redirect("clients:list-all-clients")

    return render(request, "clients/client_delete.html", {
        "client": client
    })


"""
INSURANCE VIEWS
"""


@login_required()
def insurance_detail(request, pk, id):
    """Renders insurance detail page. Client is determined by 'pk' parameter, insurance by 'id' parameter - for authenticated users"""

    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)

    return render(request, "clients/insurance_detail.html", {
        "client": client,
        "insurance": insurance
    })


@staff_member_required(login_url="/login/")
def create_insurance(request, pk):
    """Creates new insurance, that belongs to client determined by clients 'pk' parameter - only for staff users"""

    client = Client.objects.get(id=pk)
    form = CreateInsuranceForm()

    if request.method == "POST":
        form = CreateInsuranceForm(request.POST)
        if form.is_valid:
            insurance = form.save(commit=False)
            insurance.client = client
            insurance.save()
            return redirect("clients:insurance-detail", pk=insurance.client_id, id=insurance.id)

    return render(request, "clients/create_insurance.html", {
        "form": form,
        "client": client
    })


@staff_member_required(login_url="/login/")
def edit_insurance(request, pk, id):
    """Edit insurance view, that belongs to client based on 'pk' parameter - for staff users only"""
    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)
    form = CreateInsuranceForm(instance=insurance)

    if request.method == "POST":
        form = CreateInsuranceForm(request.POST, instance=insurance)
        if form.is_valid():
            form.save()
            return redirect(f"/policyholders/{client.id}/")

    return render(request, "clients/insurance_edit.html", {
        "form": form
    })


@staff_member_required(login_url="/login/")
def delete_insurance(request, pk, id):
    """Redirects to 'delete insurance confirmation page' - for staff only. CLient is determined by 'pk' parameter, insurance by 'id' parameter"""

    insurance = Insurance.objects.get(id=id)

    if request.method == "POST":
        insurance.delete()
        return redirect("clients:client-detail", pk=pk)

    return render(request, "clients/insurance_delete.html", {
        "insurance": insurance
    })

@staff_member_required(login_url="/login/")
def visa(request, pk, id):
    """View for editing client information - for staff users only. CLient is based on 'pk' parameter"""

    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)
    form = CreatePaymentForm(instance=client)

    if request.method == "POST":
        form = CreatePaymentForm(request.POST, instance=client)
        if form.is_valid:
            form.save()
            return redirect(f"/policyholders/{client.id}/insurance/{insurance.id}/payments")

    return render(request, "clients/visa.html", {
        "client": client,
        "form": form
    })

@staff_member_required(login_url="/login/")
def mastercard(request, pk, id):
    """View for editing client information - for staff users only. CLient is based on 'pk' parameter"""

    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)
    form = CreatePaymentForm(instance=client)

    if request.method == "POST":
        form = CreatePaymentForm(request.POST, instance=client)
        if form.is_valid:
            form.save()
            return redirect(f"/policyholders/{client.id}/insurance/{insurance.id}/payments")

    return render(request, "clients/mastercard.html", {
        "client": client,
        "form": form
    })

@staff_member_required(login_url="/login/")
def kaspi(request, pk, id):
    """View for editing client information - for staff users only. CLient is based on 'pk' parameter"""

    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)
    form = CreatePaymentForm(instance=client)

    if request.method == "POST":
        form = CreatePaymentForm(request.POST, instance=client)
        if form.is_valid:
            form.save()
            return redirect(f"/policyholders/{client.id}/insurance/{insurance.id}/payments")

    return render(request, "clients/kaspi.html", {
        "client": client,
        "form": form
    })

@staff_member_required(login_url="/login/")
def qiwi(request, pk, id):
    """View for editing client information - for staff users only. CLient is based on 'pk' parameter"""

    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)
    form = CreatePaymentForm(instance=client)

    if request.method == "POST":
        form = CreatePaymentForm(request.POST, instance=client)
        if form.is_valid:
            form.save()
            return redirect(f"/policyholders/{client.id}/insurance/{insurance.id}/payments")

    return render(request, "clients/qiwi.html", {
        "client": client,
        "form": form
    })

@login_required()
def payments(request, pk, id):
    """Renders insurance detail page. Client is determined by 'pk' parameter, insurance by 'id' parameter - for authenticated users"""

    client = Client.objects.get(id=pk)
    insurance = Insurance.objects.get(id=id)

    return render(request, "clients/payments.html", {
        "client": client,
        "insurance": insurance
    })

clients/templates/clients/client_delete.html
{% extends 'clients/layout.html' %}

{% block title %}Delete client{% endblock title %}

{% block section %}

    <p>Are you sure you want to delete this client? ({{ client.name }} {{ client.surname }})</p>

    <form action="" method="post">
        {% csrf_token %}
        <input class="custom-btn" type="submit" value="Delete client">
    </form>

{% endblock section %}

clients/templates/clients/client_detail.html
{% extends 'clients/layout.html' %}

{% load static %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block title %}Insurance Details{% endblock title %}

{% block section %}

    <div class="page-path">
        <a href="{% url 'clients:index' %}">Home</a>
        <p>&rsaquo;</p>
        <a href="{% url 'clients:list-all-clients' %}">List of insured persons</a> <p>&rsaquo;</p>
        <p> {{ client.name }} {{ client.surname }}</p>
    </div>


    <div class="client-detail">
        <img class="client-detail-portrait" src="{% static 'clients/user_icon.png' %}" height="150px" alt="">
        <h2 id="client-detail-name">{{ client.name }} {{ client.surname }}</h2>
        <div id="client-detail-address">
            <p>{{ client.street_address }}</p>
            <p>{{ client.city }}</p>
            <p>{{ client.postal_code }}</p>
        </div>
        <div id="client-detail-contact">
            <p>{{ client.email }}</p>
            <p>{{ client.phone_number }}</p>
        </div>
    </div>


    <div class="table-content-box">
        <div class="content-box-header table-header">
            <h2>Contractual insurance</h2>
            {% if user.is_staff %}
            <a href="{% url 'clients:create-insurance' pk=client.id %}"><img src="{% static 'clients/add_circle_blue.png' %}" alt="add circle" height="25px">Add Insurance</a>
            {% endif %}
        </div>

        <div class="custom-table">
            <table>
                {% if insurances|length > 0 %}
                <tr>
                    <th>Insurance type</th>
                    <th>Sum insured</th>
                    <th>Action</th>
                    <th></th>
                    <th></th>
                </tr>
                {% endif %}
                {% for insurance in insurances %}
                <tr>
                    <td><a href="{% url 'clients:insurance-detail' pk=client.id id=insurance.id %}">{{ insurance.get_insurance_type_display }} ({{ insurance.subject }})</a></td>
                    <td>{{ insurance.amount }} tenge</td>
                    <td>from {{ insurance.date_from|date:"d.m. Y" }} to {{ insurance.date_to|date:"d.m. Y" }}</td>
                    {% if user.is_staff %}
                    <td class="table-button"><a href="{% url 'clients:edit-insurance' pk=client.id id=insurance.id %}"><img src="{% static 'clients/edit.png' %}" height="25px" alt="edit" title="Edit"></a></td>
                    <td class="table-button"><a href="{% url 'clients:delete-insurance' pk=client.id id=insurance.id %}"><img src="{% static 'clients/delete.png' %}" height="25px" alt="delete" title="Delete"></a></td>
                    {% else %}
                    <td></td>
                    <td></td>
                    {% endif %}
                </tr>
                {% empty %}
                    <p class="empty-message">The client does not have insurance.</p>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock section %}

clients/templates/clients/clients_list.html
{% extends 'clients/layout.html' %}

{% load static %}

{% block title %}Clients{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}

<div class="page-path">
    <a href="{% url 'clients:index' %}">Home</a>
    <p>&rsaquo;</p>
    <p>List of insured persons</p>
</div>

<div class="table-content-box">
    <div class="content-box-header table-header">
        <h1>List of insured persons</h1>
        {% if user.is_staff %}
        <a href="{% url 'clients:create-client' %}"><img src="{% static 'clients/person_add_blue.png' %}" alt="add person" height="25px">Add client</a>
        {% endif %}
    </div>

    <div class="custom-table">
        <table>
        {% if paginated_clients|length > 0 %}
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th></th>
                <th></th>

            </tr>
        {% endif %}
        {% for client in paginated_clients %}
            <tr>
                <td><a href="{% url 'clients:client-detail' client.id %}">{{ client.name }} {{ client.surname }}</a></td>
                <td>{{ client.street_address }}, {{ client.city }} {{ client.postal_code }}</td>
                
                {% if user.is_staff %}
                <td class="table-button"><a href="{% url 'clients:edit-client' client.id %}"><img src="{% static 'clients/edit.png' %}" height="25px" alt="edit" title="Edit"></a></td>
                <td class="table-button"><a href="{% url 'clients:delete-client' client.id %}"><img src="{% static 'clients/delete.png' %}" height="25px" alt="delete" title="Delete"></a></td>
                {% else %}
                <td></td>
                <td></td>
                {% endif %}
            </tr>
        {% empty %}
            <p>No records.</p>
        {% endfor %}
        </table>
    </div>
</div>

<div class="pagination">
        {% if paginated_clients.has_previous %}
        <a href="?page=1" title="First page">&laquo;</a>
        <a href="?page={{ paginated_clients.previous_page_number }}">{{ paginated_clients.previous_page_number }}</a>
        {% endif %}

        <div class="current">
            {{ paginated_clients.number }}
        </div>

        {% if paginated_clients.has_next %}
        <a href="?page={{ paginated_clients.next_page_number }}">{{ paginated_clients.next_page_number }}</a>
        <a href="?page={{ paginated_clients.paginator.num_pages }}" title="Last page">&raquo;</a>
        {% endif %}
</div>

{% endblock section %}

clients/templates/clients/create_client.html
{% extends 'clients/layout.html' %}

{% block title %}Create a client{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
    <h1>New client</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="custom-btn" type="submit" value="Create a client">
    </form>

{% endblock section %}

clients/templates/clients/create_insurance.html
{% extends 'clients/layout.html' %}

{% block title %}Create insurance{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
    <h1>New insurance</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="custom-btn" type="submit" value="Create insurance">
    </form>

{% endblock section %}

clients/templates/clients/index.html
{% extends 'clients/layout.html' %}
{% load static %}
{% block navigation %}
<li><a class="active" href="{% url 'clients:index' %}">About the application</a></li>
<li><a href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}

    <h1>Welcome to the insurance management system</h1>
    <img src="{% static 'clients/pic.png' %}" width="900px">
    <p><b> Our user-friendly platform provides you with all the tools you need to stay organized and in control of your
        insurance policies. Simplify your insurance management and experience peace of mind with our efficient and
        reliable system. Get started today and let us handle the complexities while you focus on what matters most.
    </b></p>


{% endblock section %}

clients/templates/clients/insurance_delete.html
{% extends 'clients/layout.html' %}

{% block title %}Delete insurance{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}

    <p>Are you sure you want to cancel this insurance? ({{ insurance.get_insurance_type_display }} - {{ insurance.subject }})</p>

    <form action="" method="post">
        {% csrf_token %}
        <input class="custom-btn" type="submit" value="Delete insurance">
    </form>

{% endblock section %}

clients/templates/clients/insurance_detail.html
{% extends 'clients/layout.html' %}

{% load static %}

{% block title %}Insurance details{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}

<div class="page-path">
    <a href="{% url 'clients:index' %}">Home</a>
    <p>&rsaquo;</p>
    <a href="{% url 'clients:list-all-clients' %}">List of insured persons</a>
    <p>&rsaquo;</p>
    <a href="{% url 'clients:client-detail' client.id %}">{{ client.name }} {{ client.surname }}</a>
    <p>&rsaquo;</p>
    <p>{{ insurance.get_insurance_type_display }}</p>
</div>

<div class="secondary-info-box">

    <div class="content-box-header">
        <h2>{{ insurance.get_insurance_type_display }}</h2>
    </div>
    

    <table>
        <tr>
            <td>Client:</td>
            <td>{{ client.name }} {{ client.surname }}</td>
        </tr>
        <tr>
            <td>Subject of insurance:</td>
            <td>{{ insurance.subject }}</td>
        </tr>
        <tr>
            <td>Sum insured:</td>
            <td>{{ insurance.amount }} тг</td>
        </tr>
        <tr>
            <td> from:</td>
            <td>{{ insurance.date_from|date:"d.m. Y" }}</td>
        </tr>
        <tr>
            <td>Insured to:</td>
            <td>{{ insurance.date_to|date:"d.m. Y" }}</td>
        </tr>
    </table>
</div>

<div class="payments">
    <h3>Payment Methods</h3>
    <a href="visa"><img src="{% static 'clients/visa.png' %}" alt="add person" height="50px"></a>
    <a href="mastercard"><img src="{% static 'clients/mastercard.png' %}" alt="add person" height="50px"></a>
    <a href="kaspi"><img src="{% static 'clients/kaspi.png' %}" alt="add person" height="38px"></a>
    <a href="qiwi"><img src="{% static 'clients/qiwi.png' %}" alt="add person" height="50px"></a>
</div>

{% endblock section %}

clients/templates/clients/insurance_edit.html
{% extends 'clients/layout.html' %}

{% block title %}Edit Insurance{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
<h1>Insurance Adjustment</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="custom-btn" type="submit" value="Edit Insurance">
    </form>

{% endblock section %}

clients/templates/clients/kaspi.html
{% extends 'clients/layout.html' %}

{% load static %}

{% block title %}Payment{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
<h1>KASPI QR payment</h1><hr>
    <img src="{% static 'clients/qr.png' %}" alt="QR">
    <form action="payments" target="_blank">
   <button>Confirm</button>
  </form>

{% endblock section %}

clients/templates/clients/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'clients/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;600&display=swap" rel="stylesheet">
    <title>{% block title %}Clients{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'clients/house_icon.png' %}">
</head>

<body>
    <header>


        <div id="header-content" class="container">
            <a href="{% url 'clients:index' %}"><img src="{% static 'clients/app_logo.png' %}" height="50px" alt=""></a>
            <nav>
                <ul>
                    {% block navigation %}
                    <li><a href="{% url 'clients:index' %}">About the application</a></li>
                    <li><a href="{% url 'clients:list-all-clients' %}">Clients</a></li>
                    {% endblock navigation %}
                </ul>
            </nav>
            <div id="login-logout-bar" class="container">
            {% if user.is_authenticated %}
                <p id="username">{{ request.user.username }} {% if user.is_staff %} (admin) {% endif %}</p><a href="{% url 'logout' %}" class="login-logout">| Log out</a>
            {% else %}
                <a href="{% url 'login' %}" class="login-logout">Sign in </a><a href="{% url 'register' %}" id="register-btn">Register</a>
            {% endif %}
        </div>
        </div>
    </header>

    <section class="container">
        {% block section %}
        {% endblock section %}
    </section>
</body>
</html>

clients/templates/clients/mastercard.html
{% extends 'clients/layout.html' %}

{% block title %}Payment{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
<h1>MASTERCARD payment</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="custom-btn" type="submit" value="Pay">
    </form>

{% endblock section %}

clients/templates/clients/qiwi.html
{% extends 'clients/layout.html' %}

{% block title %}Payment{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
<h1>QIWI payment</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="custom-btn" type="submit" value="Pay">
    </form>

{% endblock section %}

clients/templates/clients/visa.html
{% extends 'clients/layout.html' %}

{% block title %}Payment{% endblock title %}

{% block navigation %}
<li><a  href="{% url 'clients:index' %}">About the application</a></li>
<li><a class="active" href="{% url 'clients:list-all-clients' %}">Clients</a></li>
{% endblock navigation %}

{% block section %}
<h1>VISA payment</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="custom-btn" type="submit" value="Pay">
    </form>

{% endblock section %}